import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.library)
}

group = providers.gradleProperty("pulse.group").get()
version= providers.gradleProperty("pulse.version").get()

android {
    namespace = "dev.pulse.core"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        minSdk = 24

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    resourcePrefix = "pulse_"
}

kotlin {
    explicitApi()
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    api(project(":pulse-model"))                       // type của pulse-model có trong public API
    implementation(libs.kotlinx.coroutines.android)    
    compileOnly(libs.timber)        
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
}

// Custom task: sinh PulseVersion.java cho từng variant

abstract class GeneratePulseVersionTask : DefaultTask() {
    @get:Input
    abstract val sdkVersion: Property<String>

    @get:Input
    abstract val buildType: Property<String>

    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val root = outputDirectory.get().asFile
        root.deleteRecursively()
        val dir = root.resolve(pkg.replace('.', '/')).apply { mkdirs() }
        logger.lifecycle("[EXEC]   $name -> output directory: ${dir.absolutePath}")

        dir.resolve("PulseVersion.java").writeText(
            """
            |package $pkg;
            |
            |/** GENERATED by pulse-core/build.gradle.kts — do not edit. */
            |final class PulseVersion {
            |    static final String NAME = "${sdkVersion.get()}";
            |    static final String BUILD_TYPE = "${buildType.get()}";
            |
            |    private PulseVersion() {}
            |}
            |""".trimMargin()
        )
        logger.lifecycle("[EXEC]   $name -> $pkg.PulseVersion (${sdkVersion.get()}, ${buildType.get()})")
    }
}
    androidComponents {
        onVariants { variant ->
            val taskName = "generate${variant.name.replaceFirstChar { it.uppercase() }}PulseVersion"
            val generateTask = tasks.register<GeneratePulseVersionTask>(taskName) {
                group = "pulse"
                sdkVersion.set(providers.gradleProperty("pulse.version"))
                buildType.set(variant.buildType ?: "unknown")
                packageName.set(variant.namespace)
            }
            // Tự gán outputDirectory, tự thêm vào source set, tự tạo dependency cho task compile
            variant.sources.java?.addGeneratedSourceDirectory(
                generateTask,
                GeneratePulseVersionTask::outputDirectory,
            )
        }
    }


println("[CONFIG] $path configured")